config/routes.rb
Rails.application.routes.draw do
  resources :ripples

end

app/models/ripple.rb
class Ripple < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


end

app/controllers/ripples_controller.rb
class RipplesController < ApplicationController
  before_action :set_ripple, only: [:show, :update], except: [:edit, :destroy]

  # GET /ripples
  # GET /ripples.json
  def index
    @per_page = 10

    current_page = params[:page].to_i
    a1 = current_page * @per_page
    @ripples = Ripple.order('created_at DESC').limit("#{a1}, #{@per_page}")
    @entry_count = Ripple.all.count

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @ripples}
    end
  end

    # GET /ripples/1
  # GET /ripples/1.json
  def show
  end

  # GET /ripples/new
  def new
    @ripple = Ripple.new
  end

  # POST /ripples
  # POST /ripples.json
  def create
    @ripple = Ripple.new(ripple_params)

    respond_to do |format|
      if @ripple.save
        format.html { redirect_to ripples_url, notice: 'Ripple was successfully created.' }
        format.json { head :no_content }
      else
        format.html { render :new }
        format.json { render json: @ripple.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ripples/1
  # PATCH/PUT /ripples/1.json
  def update
    respond_to do |format|
      if @ripple.update(ripple_params)
        format.html { redirect_to @ripple, notice: 'Ripple was successfully updated.' }
        format.json { render :show, status: :ok, location: @ripple }
      else
        format.html { render :edit }
        format.json { render json: @ripple.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ripple
      @ripple = Ripple.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ripple_params
      params.require(:ripple).permit(:name, :website, :message, :created_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ripples_helper.rb
module RipplesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Consciousmess</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1 id="banner">CONSCIOUS/mess <br/>
    <br/>
  ...a stream of anonymous online ramblings</h1>
<%= yield %>

</body>
</html>

app/views/ripples/_form.html.erb
<%= form_for(@ripple) do |f| %>
  <% if @ripple.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ripple.errors.entry_count, "error") %> prohibited this ripple from being saved:</h2>

      <ul>
      <% @ripple.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message, rows: 20, cols: 70 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ripples/edit.html.erb
<h1>Editing Ripple</h1>

<%= render 'form' %>

<%= link_to 'Show', @ripple %> |
<%= link_to 'Back', ripples_path %>

app/views/ripples/index.html.erb
<p id="notice"><%= notice %></p>

<p class = "invisible">
  <%= count = @entry_count%>
<!-- total pages -->
<% pages = @entry_count / @per_page %>
<!-- the last page -->

<% if pages % @per_page > 0 %>
  <% pages = pages + 1 %>
<% end %>

<% current = params[:page].to_i %>
<% if current <= pages - 2 %>
  <% next_page = current + 1 %>
<% else %>
  <% next_page = current %>
<% end %>

<% current = params[:page].to_i %>
<% if current > 0 %>
  <% previous_page = current - 1 %>
<% else %>
  <% previous_page = current %>
<% end %>



<p class = "invisible">
<% (0..(pages-1)).each do |i| %>
    <!-- href or link_to, http://xxxxxxxx/yyyy?page=i -->
    <%= link_to i+1, :action => "index", :controller => "ripples", :page => i %>
<% end %>
</p>

<table>
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ripples.each do |ripple| %>
      <tr>
        <td><%= count - params[:page].to_i * @per_page %><% count = count - 1 %></td>
        <% if ripple.website.blank? %>
            <td><%= ripple.name %></td>
        <% else %>
            <td><%= link_to ripple.name, ripple.website %></td>
        <% end %>
        <td><%= ripple.message %></td>
        <td><%= link_to 'Show', ripple %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div style="text-align: center">
  <%= link_to 'Newest', :page => 0 %>
  <span style ="padding: 5px;"> | </span>
  <%= link_to 'Previous 10 Ripples', :page => previous_page %>
  <span style ="padding: 5px;"> | </span>
  <%= link_to 'Next 10 Ripples',  :page => next_page %>
  <span style ="padding: 5px;"> | </span>
  <%= link_to 'Oldest', :page => pages - 1 %>
  <span style ="padding: 5px;"> | </span>
  <%= link_to 'New Ripple', new_ripple_path %>
</div>

app/views/ripples/new.html.erb
<h1>New Ripple</h1>

<%= render 'form' %>

<%= link_to 'Back', ripples_path %>

app/views/ripples/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <a id = "alias">
    <%= @ripple.name %>
  </a>
  <a id = "said">
    <%= '  said:' %>
  </a>

</p>


<p class = "message">

  <%= @ripple.message %>
</p>

<p class = link>
  <% if @ripple.website.blank? %>
  <% else %>
    <td><%= link_to @ripple.website, @ripple.website %></td>
<% end %>
</p>


<%= link_to 'Back to List', ripples_path %>